VM_MEMORY = 512 # Amount of RAM (in MB) allocated to each VM
VM_CPUs = 1 # Number of CPU cores assigned to each VM
VM_BOX = "generic/ubuntu1804" # Base box (Ubuntu 18.04 image) to use for each VM
VM_BOX_VERSION = "4.3.12" # Specific version of the base box to use
BASE_IP = "192.168.56." # Base IP range for assigning static private IPs to the VMs
PORT = 9000 # Starting host port for forwarding to guest port 80 (HTTP)
HOSTNAME = "chessgame" # Base hostname prefix for naming each VM

Vagrant.configure("2") do |config| 
  (1..3).each do |i| # Loop to create 3 virtual machines 
    config.vm.define "web#{i}" do |node| # Define each VM with a unique name(web1, web2, web3)
      node.vm.box = VM_BOX # Use the specified base box
      node.vm.box_version = VM_BOX_VERSION # Use the specified version of the base box
      node.vm.synced_folder "../chessgame", "/var/www/html" # Sync project folder from host to VM web directory(if you cloned the entire repository, you're set, otherwise please download the folder "chessgame" to see the content)
      node.vm.network "forwarded_port", guest:80, host: PORT + i - 1, auto_correct: false # Forward host ports(9000, 9001, ..) to guest port 80(The formula was just a preference, remove if you want)
      node.vm.hostname = "#{HOSTNAME}#{i}.com" # Assign unique hostname to each VM(example: chessgame1.com,..)
      node.vm.network "private_network", ip: "#{BASE_IP}#{10 + i - 1}" # Assign static private IPs(example: 192.168.56.10; .11; .12)(Again, the formula was just a preference. Remove if you want)
      node.vm.provider "virtualbox" do |vb|
        vb.memory = VM_MEMORY # Set VM memory allocation
        vb.cpus = VM_CPUs # Set number of CPU cores
      end
      node.vm.provision "shell", run:"once", inline: <<-SHELL # Run shell script 
        sudo apt-get update -y # Update package list
        sudo apt-get install nginx -y # Install Nginx web server
        sudo systemctl enable nginx # Enable Nginx to start on boot
        sudo systemctl restart nginx # Restart Nginx service
        sudo rm -f /var/www/html/index.nginx-debian.html # Remove default Nginx welcome page
      SHELL
    end
  end
end